language: rust

rust:
- 1.13.0
- stable
- nightly

os:
  - linux

script:
  - cargo build --verbose
  - if [[ $TRAVIS_RUST_VERSION = nightly* ]]; then
      env RUST_BACKTRACE=1 cargo test -v;
    fi
